// angular/src/app/components/bootstrap/confirm-modal/confirm-modal.component.ts
import {Component, OnInit, ViewChild} from '@angular/core';
import {LocalBootstrapService} from "../local-bootstrap.service";
import {ModalDirective} from "ngx-bootstrap";
import {ConfirmModal} from "./confirm-modal.interface";

@Component({
    selector: 'app-confirm-modal',
    templateUrl: './confirm-modal.component.html',
    styles: []
})
export class ConfirmModalComponent implements OnInit {
    @ViewChild('staticModal')
    staticModal: ModalDirective;
    confirmMessage: string;
    item: ConfirmModal;

    constructor(private localBootstrapService: LocalBootstrapService) {
    }

    ngOnInit() {
        this.localBootstrapService.getConfirmModalObservable().subscribe(item => this.show(item));
    }

    show(item) {
        this.item = item;
        this.confirmMessage = item.message;
        this.staticModal.show();
    }

    onConfirm() {
        this.item.success();
        this.staticModal.hide();
    }

    onHidden() {
        this.confirmMessage = '';
        this.item = null;
    }

}

<div class="modal fade" bsModal #staticModal="bs-modal" [config]="{backdrop: 'static'}" (onHidden)="onHidden()"
     tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title pull-left">Static modal</h4>
                <button type="button" class="close pull-right" aria-label="Close" (click)="staticModal.hide()">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{confirmMessage}}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" (click)="staticModal.hide()">Cancel</button>
                <button type="button" class="btn btn-success" (click)="onConfirm()">Confirm</button>
            </div>
        </div>
    </div>
</div>

// react/src/components/bootstrap/confirmModal.js
import React from "react";
export default  (props) => (
    <div className={"modal fade "} role="dialog" id="confirmModal"
         aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div className="modal-dialog modal-sm">
            <div className="modal-content">
                <div className="modal-header">
                    <h4 className="modal-title pull-left">Confirm</h4>
                    <button type="button" className="close pull-right" aria-label="Close" onClick={props.closeConfirmModal}>
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div className="modal-body">
                    {props.confirmModal.message}
                </div>
                <div className="modal-footer">
                    <button type="button" className="btn btn-danger"  onClick={props.closeConfirmModal}>Cancel</button>
                    <button type="button" className="btn btn-success" onClick={props.confirmModal.onConfirm}>Confirm
                    </button>
                </div>
            </div>
        </div>
    </div>
)
