// angular/src/app/components/login/login.component.ts
import {Component, OnInit} from '@angular/core';
import {Title} from "@angular/platform-browser";
import {FormBuilder, FormGroup, Validators} from "@angular/forms";
import {LocalApiService} from "../../services/local-api.service";
import {LocalBootstrapService} from "../bootstrap/local-bootstrap.service";
import {ActivatedRoute, Router} from "@angular/router";
import {AuthService} from "../../services/auth.service";

@Component({
    selector: 'app-login',
    templateUrl: './login.component.html',
    styles: [],
})
export class LoginComponent implements OnInit {
    loginForm: FormGroup;
    formSubmitted: boolean;
    validData: boolean;

    constructor(private title1: Title,
                private pageTitle: Title,
                private formBuilder: FormBuilder,
                private localApi: LocalApiService,
                private authService: AuthService,
                private localBootstrap: LocalBootstrapService,
                private activeRoute: ActivatedRoute,
                private router: Router) {
    }

    ngOnInit() {
        this.title1.setTitle('Dashboard Login');
        this.formSubmitted = false;
        this.validData = true;

        this.loginForm = this.formBuilder.group({
            email: ['admin@mina.com', [Validators.required]],
            password: ['123123', [Validators.required]],
        })
    }

    onLoginSubmit() {
        this.formSubmitted = true;
        if (this.loginForm.valid) {
            const user = {
                email: this.loginForm.value.email,
                password: this.loginForm.value.password,
            }
            this.localApi.loginUser(user).subscribe(data => {
                if (data.success) {
                    this.localBootstrap.notifySuccess('Welcome to dashboard');
                    this.authService.storeUserData(data.token, data.user);
                    this.router.navigate(['dashboard']);
                } else {
                    this.validData = false;
                }
            })
        }
    }
}

<div class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="javascript:;"><b>Admin</b>LTE</a>
        </div>
        <!-- /.login-logo -->
        <div class="login-box-body">
            <p class="login-box-msg">Sign in to start your session</p>
            <div *ngIf="formSubmitted && (!loginForm.valid || !validData)"
                 class="alert alert-danger alert-dismissible ">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                Invalid username or password.
            </div>

            <form (submit)="onLoginSubmit()" [formGroup]="loginForm">
                <div class="form-group has-feedback"
                     [ngClass]="{'has-error':loginForm.controls['email'].touched && !loginForm.controls['email'].valid }">
                    <input type="text" class="form-control" placeholder="Email" formControlName="email">
                    <span class="glyphicon glyphicon-envelope form-control-feedback"
                          *ngIf="loginForm.controls['email'].touched && loginForm.controls['email'].hasError('required')">
                                Required</span>

                </div>
                <div class="form-group has-feedback"
                     [ngClass]="{'has-error':loginForm.controls['password'].touched && !loginForm.controls['password'].valid }">
                    <input type="password" class="form-control" placeholder="Password" formControlName="password">

                </div>
                <div class="row">
                    <div class="col-xs-8">

                    </div>
                    <!-- /.col -->
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>
        </div>
        <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->
</div>

// react/src/components/login/Login.js
import React from "react";
import { connect } from "react-redux";
import LoginForm from "./LoginForm";

export default props =>
  <div className="hold-transition login-page">
    <div className="login-box">
      <div className="login-logo">
        <a href="javascript:;"><b>Admin</b>LTE</a>
      </div>
      <div className="login-box-body">
        <p className="login-box-msg">Sign in to start your session</p>
        <div
          className="alert alert-danger alert-dismissible "
          style={{ display : !props.hasError ? "none" : ""}}
        >
          <button
            aria-hidden="true"
            data-dismiss="alert"
            className="close"
            type="button"
          />
          Invalid username or password.
        </div>
        <LoginForm onSubmit={props.onSubmit} />
      </div>
    </div>
  </div>;
