// angular/src/app/components/product-form/product-form.component.ts
import {Component, OnInit, AfterViewInit, ViewChild, ElementRef} from '@angular/core';
import {Title} from "@angular/platform-browser";
import {FormBuilder, FormGroup, Validators} from "@angular/forms";
import {LocalApiService} from "../../services/local-api.service";
import {ActivatedRoute, Router} from "@angular/router";
import {LocalBootstrapService} from "../bootstrap/local-bootstrap.service";
declare var $: any;

@Component({
    selector: 'app-product-form',
    templateUrl: './product-form.component.html',
    styles: []
})
export class ProductFormComponent implements OnInit, AfterViewInit {

    productForm: FormGroup;
    productImage: any = null;
    productImageTouched: any = null;
    productId: Number;
    imagesUrl: String;
    uploadImage: String;
    oldProduct: any = null;
    @ViewChild('inputProductImage') inputProductImage: ElementRef;

    constructor(private pageTitle: Title,
                private formBuilder: FormBuilder,
                private localApi: LocalApiService,
                private localBootstrap: LocalBootstrapService,
                private activeRoute: ActivatedRoute,
                private router: Router) {
    }

    ngOnInit() {
        this.imagesUrl = this.localApi.getProductImageUrl();
        this.uploadImage = this.imagesUrl;
        this.productForm = this.formBuilder.group({
            title: ['', [Validators.required, Validators.minLength(4)]],
            description: ['', [Validators.required, Validators.minLength(4)]],
            price: ['', [Validators.required, Validators.pattern(/^(\d+(\.\d+)?)$/)]],
        })

        this.activeRoute.params.subscribe(params => {
            if (params.id) {
                this.pageTitle.setTitle('Edit Product');
                this.localApi.getProduct(params.id).subscribe(e => {
                    this.oldProduct = e;
                    this.productForm.patchValue(this.oldProduct);
                    this.productImage = this.oldProduct.imagePath;
                    this.uploadImage = this.imagesUrl + this.oldProduct.imagePath;
                });
            }
            else {
                this.pageTitle.setTitle('Add Product');
            }

        });
    }

    ngAfterViewInit(): void {
        $(this.inputProductImage.nativeElement).fileinput();
    }

    fileUpload(event: any) {
        var file = event.target.files[0];
        if (file) {
            this.productImageTouched = true;
            if (['image/jpg', 'image/jpeg', 'image/png'].indexOf(file.type) != -1) {
                this.productImage = event.target.files[0];

                let reader: FileReader = new FileReader();
                reader.onload = (e: any) => this.uploadImage = e.target.result;
                reader.readAsDataURL(this.productImage);
            }
        }
    }

    onSubmit() {
        if (!this.productImage || !this.productForm.valid) {
            Object.keys(this.productForm.controls).forEach(key => {
                this.productForm.get(key).markAsTouched();
            });
        }
        else {
            this.localBootstrap.showLoader();
            var product = this.productForm.value;
            let formData: FormData = new FormData();
            for (let key in this.productForm.value) {
                formData.append(key, this.productForm.value[key]);
            }
            if (!this.oldProduct || this.productImage != this.oldProduct.imagePath) {
                formData.append('upload', this.productImage, this.productImage.name);
            }

            if (this.oldProduct) {

                this.localApi.updateProduct(this.oldProduct._id, formData).subscribe(res => {
                    this.localBootstrap.hideLoader();
                    this.localBootstrap.notify({message: 'Product updated successfully', type: 'success'});
                })
            }
            else {
                this.localApi.addProduct(formData).subscribe(res => {
                    this.localBootstrap.hideLoader();
                    this.localBootstrap.notify({message: 'Product added successfully', type: 'success'});
                    this.router.navigate(['/products']);
                })
            }
        }
    }

    goToProductList() {
        this.router.navigate(['/products']);
    }
}

<div class="row">

    <div class="col-md-6">
        <!-- Horizontal Form -->
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Product</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" [formGroup]="productForm" (submit)="onSubmit()">
                <div class="box-body">
                    <div class="form-group"
                         [ngClass]="{'has-error':productForm.controls['title'].touched && !productForm.controls['title'].valid }">
                        <label class="col-sm-2 control-label">Title</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" formControlName="title"/>
                            <span class="help-block"
                                  *ngIf="productForm.controls['title'].touched && productForm.controls['title'].hasError('required')">
                                This filed is required
                            </span>
                            <span class="help-block"
                                  *ngIf="productForm.controls['title'].touched && productForm.controls['title'].hasError('minlength')">
                                This filed minimum length 4 characters
                            </span>
                        </div>
                    </div>
                    <div class="form-group"
                         [ngClass]="{'has-error':productForm.controls['description'].touched && !productForm.controls['description'].valid }">
                        <label class="col-sm-2 control-label">Description</label>
                        <div class="col-sm-10">
                            <textarea type="text" class="form-control" formControlName="description"></textarea>
                            <span class="help-block"
                                  *ngIf="productForm.controls['description'].touched && productForm.controls['description'].hasError('required')">
                                This filed is required
                            </span>
                            <span class="help-block"
                                  *ngIf="productForm.controls['description'].touched && productForm.controls['description'].hasError('minlength')">
                                This filed minimum length 4 characters
                            </span>
                        </div>
                    </div>
                    <div class="form-group"
                         [ngClass]="{'has-error':productForm.controls['price'].touched && !productForm.controls['price'].valid }">
                        <label class="col-sm-2 control-label">Price</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" formControlName="price"/>
                            <span class="help-block"
                                  *ngIf="productForm.controls['price'].touched && productForm.controls['price'].hasError('required')">
                                This filed is required
                            </span>
                            <span class="help-block"
                                  *ngIf="productForm.controls['price'].touched && productForm.controls['price'].hasError('pattern')">
                                This filed must be number
                            </span>
                        </div>
                    </div>
                    <div class="form-group"
                         [ngClass]="{'has-error':productImageTouched && !productImage }">
                        <label class="col-sm-2 control-label">Image</label>
                        <div class="col-sm-10">
                            <input #inputProductImage type="file"
                                   data-show-upload="false"
                                   data-show-remove="false"
                                   data-show-preview="false"
                                   data-max-file-size="2048k"
                                   data-allowed-file-extensions='["jpg","jpeg", "png"]'
                                   (change)="fileUpload($event)" (click)="fileUpload($event)">
                            <span class="help-block" *ngIf="productImageTouched && !productImage">
                                 Valid image with max size 2M required
                            </span>
                        </div>
                    </div>

                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="button" class="btn btn-default" (click)="goToProductList()">Cancel
                        </button>
                        <button type="submit" class="btn btn-info pull-right">Save
                        </button>
                    </div>
                </div>
                <!-- /.box-footer -->
            </form>
        </div>
        <!-- /.box -->
        <!-- /.box-body -->
    </div>
    <div class="col-md-6">
        <!-- Horizontal Form -->
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Product Image</h3>
            </div>
            <div class="box-body">
                <div class="col-md-11">
                    <div class="thumbnail">
                        <img src="{{uploadImage}}" >
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.box -->
</div>

// react/src/components/product/ProductForm.js
import React from "react";
import { Field, reduxForm } from "redux-form";
import Validate from "../../form/FormValidations";

const renderField = ({
  input,
  label,
  type,
  meta: { touched, error, warning }
}) =>
  <div className={touched && error ? "form-group has-error" : "form-group"}>
    <label className="col-sm-2 control-label">{label}</label>
    <div className="col-sm-10">
      {type == "textarea"
        ? <textarea {...input} placeholder={label} className="form-control">
            {/*data*/}
          </textarea>
        : <input
            {...input}
            placeholder={label}
            type={type}
            className="form-control"
          />}
      {touched &&
        ((error && <span className="help-block">{error}</span>) ||
          (warning && <span className="help-block">{warning}</span>))}
    </div>
  </div>;

const FieldLevelValidationForm = props => {
  const { handleSubmit, pristine, reset, submitting } = props;
  return (
    <form className="form-horizontal" onSubmit={handleSubmit}>
      <div className="box-body">
        <Field
          name="title"
          type="text"
          component={renderField}
          label="Title"
          validate={[Validate.required, Validate.minLength(4)]}
        />
        <Field
          name="description"
          type="textarea"
          component={renderField}
          label="Description"
          validate={[Validate.required, Validate.minLength(4)]}
        />
        <Field
          name="price"
          type="text"
          component={renderField}
          label="Price"
          validate={[Validate.required, Validate.number]}
        />
        <div
          className={
            props.productImageTouched && !props.productImage
              ? "form-group has-error"
              : "form-group"
          }
        >
          <label className="col-sm-2 control-label">Image</label>
          <div className="col-sm-10">
            <input
              className="file"
              id="inputProductImage"
              type="file"
              data-show-upload="false"
              data-show-remove="false"
              data-show-preview="false"
              data-max-file-size="2048k"
              data-allowed-file-extensions="[&quot;jpg&quot;,&quot;jpeg&quot;, &quot;png&quot;]"
              onChange={props.fileUpload}
              onClick={props.fileUpload}
            />
            <span
              className="help-block"
              style={{
                display: props.productImageTouched && !props.productImage
                  ? ""
                  : "none"
              }}
            >
              Please add valid image with max size 2M required
            </span>
          </div>
        </div>
        <div className="box-footer">
          <button type="button" className="btn btn-default">
            Cancel
          </button>
          <button type="submit" className="btn btn-info pull-right">
            Save
          </button>
        </div>
      </div>
    </form>
  );
};

export default reduxForm({
  form: "fieldLevelValidation", // a unique identifier for this form
  enableReinitialize: true
})(FieldLevelValidationForm);
