// angular/src/app/components/admin-form/admin-form.component.ts
import {Component, OnInit, AfterViewInit, ViewChild, ElementRef} from '@angular/core';
import {Title} from "@angular/platform-browser";
import {AsyncValidator, FormBuilder, FormControl, FormGroup, ValidationErrors, Validators} from "@angular/forms";
import {LocalApiService} from "../../services/local-api.service";
import {ActivatedRoute, Router} from "@angular/router";
import {LocalBootstrapService} from "../bootstrap/local-bootstrap.service";
declare var $: any;

@Component({
    selector: 'app-admin-form',
    templateUrl: './admin-form.component.html',
})
export class AdminFormComponent implements OnInit, AfterViewInit {

    adminForm: FormGroup;
    adminId: Number;
    oldAdminData: any = null;
    @ViewChild('input') input: ElementRef[];
    @ViewChild('input1') input1: ElementRef;
    @ViewChild('input2') input2: ElementRef;
    @ViewChild('input3') input3: ElementRef;
    @ViewChild('input4') input4: ElementRef;

    constructor(private pageTitle: Title,
                private formBuilder: FormBuilder,
                private localApi: LocalApiService,
                private localBootstrap: LocalBootstrapService,
                private activeRoute: ActivatedRoute,
                private router: Router) {
    }

    validateEmailDuplicated() {
        return (control: FormControl) => {
            return this.localApi.checkAdminEmailExist(control.value, this.oldAdminData ? this.oldAdminData._id : '').map(res => {
                if (res.exist) {
                    return {'duplicated': true}
                }
                return null;
            })
        }
    }

    ngOnInit() {
        this.adminForm = this.formBuilder.group({
            name: ['', [Validators.required, Validators.minLength(4)]],
            email: ['', [Validators.required, Validators.email], [this.validateEmailDuplicated()]],
            password: ['', [Validators.required, Validators.minLength(4)]],
            confirmPassword: ['', [Validators.required]],
            isSuperAdmin: [''],
            roles: this.formBuilder.group({
                admins: ['', [Validators.required]],
                products: ['', [Validators.required]],
                orders: ['', []],
            })
        })

        this.activeRoute.params.subscribe(params => {
            if (params.id) {
                this.pageTitle.setTitle('Edit Admin');
                this.localApi.getAdminData(params.id).subscribe(e => {
                    this.oldAdminData = e;
                    console.log(this.oldAdminData.roles)
                    this.adminForm.patchValue(this.oldAdminData);
                    $('.adminForm').find('input').iCheck('update');
                });
                this.adminForm.controls['password'].clearValidators()
                this.adminForm.controls['password'].setValidators(Validators.minLength(4));
                this.adminForm.controls['confirmPassword'].clearValidators();

            }
            else {
                this.pageTitle.setTitle('Add Admin');
                this.adminForm.patchValue({
                    isSuperAdmin: 1,
                    admins_role: 'view',
                    products_role: 'view'
                });
            }

        });
    }

    ngAfterViewInit(): void {
        $('.adminForm').find('input[type=radio]').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        }).on('ifChecked', (event) => {
            // console.log(this.adminForm.controls.roles['controls']);
            this.adminForm.controls.roles['controls'][$(event.target).attr('name')].patchValue($(event.target).val());
        });
        $('.adminForm').find('input[type=checkbox]').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        }).on('ifChanged', (event) => {
            this.adminForm.controls[$(event.target).attr('name')].patchValue($(event.target).prop('checked'));
        })
    }

    onSubmit() {
        if ((this.adminForm.controls['confirmPassword'].value != this.adminForm.controls['password'].value) || !this.adminForm.valid) {
            Object.keys(this.adminForm.controls).forEach(key => {
                this.adminForm.get(key).markAsTouched();
            });
        }
        else {
            this.localBootstrap.showLoader();

            if (this.oldAdminData) {

                this.localApi.updateAdmin(this.oldAdminData._id, this.adminForm.value).subscribe(res => {
                    this.localBootstrap.hideLoader();
                    this.localBootstrap.notify({message: 'Admin updated successfully', type: 'success'});
                })
            }
            else {
                this.localApi.addAdmin(this.adminForm.value).subscribe(res => {
                    this.localBootstrap.hideLoader();
                    this.localBootstrap.notify({message: 'Admin added successfully', type: 'success'});
                    this.router.navigate(['/admins']);
                })
            }
        }
    }

    goToAdminsList() {
        this.router.navigate(['/admins']);
    }

}

<div class="row">

    <div class="col-md-6">
        <!-- Horizontal Form -->
        <div class="box box-success">
            <div class="box-header with-border">
                <h3 class="box-title">Product</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal adminForm" [formGroup]="adminForm" (submit)="onSubmit()">
                <div class="box-body">
                    <div class="form-group"
                         [ngClass]="{'has-error':adminForm.controls['name'].touched && !adminForm.controls['name'].valid }">
                        <label class="col-sm-2 control-label">Name</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" formControlName="name"/>
                            <span class="help-block"
                                  *ngIf="adminForm.controls['name'].touched && adminForm.controls['name'].hasError('required')">
                                This filed is required
                            </span>
                            <span class="help-block"
                                  *ngIf="adminForm.controls['name'].touched && adminForm.controls['name'].hasError('minlength')">
                                This filed minimum length 4 characters
                            </span>
                        </div>
                    </div>
                    <div class="form-group"
                         [ngClass]="{'has-error':adminForm.controls['email'].touched && !adminForm.controls['email'].valid && !adminForm.controls['email'].pending }">
                        <label class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" formControlName="email"/>
                            <span class="help-block"
                                  *ngIf="adminForm.controls['email'].touched && adminForm.controls['email'].hasError('required')">
                                This filed is required
                            </span>
                            <span class="help-block"
                                  *ngIf="adminForm.controls['email'].touched && adminForm.controls['email'].hasError('email') && !adminForm.controls['email'].hasError('required')">
                                This filed must be in email format
                            </span>
                            <span class="help-block"
                                  *ngIf="adminForm.controls['email'].hasError('duplicated')">
                                This email already exist
                            </span>
                            <span class="help-block"
                                  *ngIf="adminForm.controls['email'].pending">Checking duplication...</span>
                        </div>
                    </div>

                    <div class="form-group"
                         [ngClass]="{'has-error':adminForm.controls['password'].touched && !adminForm.controls['password'].valid }">
                        <label class="col-sm-2 control-label">Password</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" formControlName="password"/>
                            <span class="help-block"
                                  *ngIf="adminForm.controls['password'].touched && adminForm.controls['password'].hasError('required')">
                                This filed is required
                            </span>
                            <span class="help-block"
                                  *ngIf="adminForm.controls['password'].touched && adminForm.controls['password'].hasError('minlength')">
                               This filed minimum length 4 characters
                            </span>
                        </div>
                    </div>
                    <div class="form-group"
                         [ngClass]="{'has-error':
                         adminForm.controls['confirmPassword'].touched &&
                         (adminForm.controls['confirmPassword'].value != adminForm.controls['password'].value || !adminForm.controls['confirmPassword'].valid) &&
                         adminForm.controls['password'].valid}">
                        <label class="col-sm-2 control-label">Confirm Password</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" formControlName="confirmPassword"/>
                            <span class="help-block"
                                  *ngIf="adminForm.controls['confirmPassword'].touched && adminForm.controls['confirmPassword'].hasError('required') && adminForm.controls['password'].valid">
                                This filed is required
                            </span>
                            <span class="help-block"
                                  *ngIf="adminForm.controls['confirmPassword'].touched && adminForm.controls['confirmPassword'].value && adminForm.controls['confirmPassword'].value != adminForm.controls['password'].value && adminForm.controls['password'].valid">
                                Password is not matched
                            </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" class="minimal" name="isSuperAdmin" id="role"
                                           formControlName="isSuperAdmin" value="1"> Super Admin
                                </label>
                            </div>
                        </div>
                    </div>
                    <div formGroupName="roles">
                        <div class="form-group" [style.display]="adminForm.controls.isSuperAdmin.value ? 'none' :'' ">
                            <label class="col-sm-2 control-label">Admins Role</label>
                            <div class="col-sm-offset-2 col-sm-8">
                                <label>
                                    <input type="radio" formControlName="admins" name="admins" value="view">
                                    View Only
                                </label>
                                <label>
                                    <input type="radio" formControlName="admins" name="admins" value="manage">
                                    Manage admins
                                </label>
                            </div>
                        </div>
                        <div class="form-group" [style.display]="adminForm.controls.isSuperAdmin.value ? 'none' :'' ">
                            <label class="col-sm-2 control-label">Products Role</label>
                            <div class="col-sm-offset-2 col-sm-8">
                                <label>
                                    <input type="radio" formControlName="products" name="products"
                                           value="view"
                                    >
                                    View Only
                                </label>
                                <label>
                                    <input type="radio" formControlName="products" name="products"
                                           value="manage"
                                    >
                                    Manage products
                                </label>
                            </div>
                        </div>
                        <div class="form-group" [style.display]="adminForm.controls.isSuperAdmin.value ? 'none' :'' ">
                            <label class="col-sm-2 control-label">Orders Role</label>
                            <div class="col-sm-offset-2 col-sm-8">
                                <label>
                                    <input type="radio" formControlName="orders" name="orders"
                                           value="view">
                                    View
                                </label>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="button" class="btn btn-default" (click)="goToAdminsList()">Cancel
                        </button>
                        <button type="submit" class="btn btn-info pull-right">
                            Save
                        </button>
                    </div>
                </div>
                <!-- /.box-footer -->
            </form>
        </div>
        <!-- /.box -->
        <!-- /.box-body -->
    </div>

    <!-- /.box -->
</div>

// react/src/components/admin/AdminForm.js
import React from "react";
import {Field, getFormValues, reduxForm} from "redux-form";
import Validate from "../../form/FormValidations";

const renderField = ({
                         input,
                         label,
                         type,
                         meta: {touched, error, warning}
                     }) =>
    <div className={touched && error ? "form-group has-error" : "form-group"}>
        <label className="col-sm-2 control-label ">{label}</label>
        <div className="col-sm-10">
            {type == "textarea"
                ? <textarea {...input} placeholder={label} className="form-control">
            {/*data*/}
          </textarea>
                : <Field component="input"
                         {...input}
                         placeholder={label}
                         type={type}
                         className="form-control"
                />}
            {touched &&
            ((error && <span className="help-block">{error}</span>) ||
            (warning && <span className="help-block">{warning}</span>))}
        </div>
    </div>;

const AdminForm = props => {
    const {handleSubmit, pristine, reset, submitting} = props;
    return (
        <form className="form-horizontal adminForm" onSubmit={handleSubmit}>
            <div className="box-body">
                <Field
                    name="name"
                    type="text"
                    component={renderField}
                    label="Name"
                    validate={[Validate.required, Validate.minLength(4)]}
                />
                <Field
                    name="email"
                    type="text"
                    component={renderField}
                    label="Email"
                    validate={[Validate.required, Validate.email()]}
                />
                <Field
                    name="password"
                    type="password"
                    component={renderField}
                    label="Password"
                    validate={[Validate.required, Validate.minLength(4)]}
                />
                <Field
                    name="confirmPassword"
                    type="password"
                    component={renderField}
                    label="Confirm Password"
                    validate={[Validate.required]}
                />
                <div className="form-group">
                    <div className="col-sm-offset-2 col-sm-10">
                        <div className="checkbox">
                            <label>
                                <Field component="input" type="checkbox" className="minimal" name="isSuperAdmin"
                                       id="role"
                                       value="1"/> Super Admin
                            </label>
                        </div>
                    </div>
                </div>
                <div className="form-group" style={{display: props.isSuperAdmin ? 'none' : ''}}>
                    <label className="col-sm-2 control-label" style={{"padding-top":"0px"}}>Admins Role</label>
                    <div className=" col-sm-8">
                        <label>
                            <Field component="input" type="radio" name="admins" value="view"/>
                            View Only
                        </label>
                        <label>
                            <Field component="input" type="radio" name="admins" value="manage"/>
                            Manage admins
                        </label>
                    </div>
                </div>
                <div className="form-group" style={{display: props.isSuperAdmin ? 'none' : ''}}>
                    <label className="col-sm-2 control-label" style={{"padding-top":"0px"}}>Products Role</label>
                    <div className=" col-sm-8">
                        <label>
                            <Field component="input" type="radio" name="products"
                                   value="view"
                            />
                            View Only
                        </label>
                        <label>
                            <Field component="input" type="radio" name="products"
                                   value="manage"
                            />
                            Manage products
                        </label>
                    </div>
                </div>
                <div className="form-group" style={{display: props.isSuperAdmin ? 'none' : ''}}>
                    <label className="col-sm-2 control-label" style={{"padding-top":"0px"}}>Orders Role</label>
                    <div className="col-sm-8">
                        <label>
                            <Field component="input" type="radio" name="orders"
                                   value="view"/>
                            View
                        </label>
                    </div>
                </div>
                <div className="box-footer">
                    <button type="button" className="btn btn-default">Cancel
                    </button>
                    <button type="submit" className="btn btn-info pull-right">
                        Save
                    </button>
                </div>
            </div>

        </form >
    );
};

export default reduxForm({
    form: "AdminForm", // a unique identifier for this form
    enableReinitialize: true
})(AdminForm);
